require "Items/ProceduralDistributions"
require "Items/Distributions"

local function lowhealthringesspawn()
    table.insert(ProceduralDistributions.list.ArmyStorageMedical.items, "RustRinges.PercentTenRinge")
    table.insert(ProceduralDistributions.list.ArmyStorageMedical.items, 17)
    table.insert(ProceduralDistributions.list.ArmyStorageMedical.items, "RustRinges.PercentTwentyfiveRinge")
    table.insert(ProceduralDistributions.list.ArmyStorageMedical.items, 11.2)
    table.insert(ProceduralDistributions.list.ArmyStorageMedical.items, "RustRinges.PercentFiftyRinge")
    table.insert(ProceduralDistributions.list.ArmyStorageMedical.items, 8.5)

    table.insert(ProceduralDistributions.list.BathroomCabinet.items, "PercentTenRinge")
    table.insert(ProceduralDistributions.list.BathroomCabinet.items, 17)
    table.insert(ProceduralDistributions.list.BathroomCabinet.items, "RustRinges.PercentTwentyfiveRinge")
    table.insert(ProceduralDistributions.list.BathroomCabinet.items, 11.2)
    table.insert(ProceduralDistributions.list.BathroomCabinet.items, "RustRinges.PercentFiftyRinge")
    table.insert(ProceduralDistributions.list.BathroomCabinet.items, 8.5)

    table.insert(ProceduralDistributions.list.BathroomCounter.items, "PercentTenRinge")
    table.insert(ProceduralDistributions.list.BathroomCounter.items, 17)
    table.insert(ProceduralDistributions.list.BathroomCounter.items, "RustRinges.PercentTwentyfiveRinge")
    table.insert(ProceduralDistributions.list.BathroomCounter.items, 11.2)
    table.insert(ProceduralDistributions.list.BathroomCounter.items, "RustRinges.PercentFiftyRinge")
    table.insert(ProceduralDistributions.list.BathroomCounter.items, 8.5)

    table.insert(ProceduralDistributions.list.BathroomShelf.items, "PercentTenRinge")
    table.insert(ProceduralDistributions.list.BathroomShelf.items, 17)
    table.insert(ProceduralDistributions.list.BathroomShelf.items, "RustRinges.PercentTwentyfiveRinge")
    table.insert(ProceduralDistributions.list.BathroomShelf.items, 11.2)
    table.insert(ProceduralDistributions.list.BathroomShelf.items, "RustRinges.PercentFiftyRinge")
    table.insert(ProceduralDistributions.list.BathroomShelf.items, 8.5)

    table.insert(ProceduralDistributions.list.MedicalClinicDrugs.items, "PercentTenRinge")
    table.insert(ProceduralDistributions.list.MedicalClinicDrugs.items, 17)
    table.insert(ProceduralDistributions.list.MedicalClinicDrugs.items, "RustRinges.PercentTwentyfiveRinge")
    table.insert(ProceduralDistributions.list.MedicalClinicDrugs.items, 11.2)
    table.insert(ProceduralDistributions.list.MedicalClinicDrugs.items, "RustRinges.PercentFiftyRinge")
    table.insert(ProceduralDistributions.list.MedicalClinicDrugs.items, 8.5)

    table.insert(ProceduralDistributions.list.MedicalClinicOutfit.items, "PercentTenRinge")
    table.insert(ProceduralDistributions.list.MedicalClinicOutfit.items, 17)
    table.insert(ProceduralDistributions.list.MedicalClinicOutfit.items, "RustRinges.PercentTwentyfiveRinge")
    table.insert(ProceduralDistributions.list.MedicalClinicOutfit.items, 11.2)
    table.insert(ProceduralDistributions.list.MedicalClinicOutfit.items, "RustRinges.PercentFiftyRinge")
    table.insert(ProceduralDistributions.list.MedicalClinicOutfit.items, 8.5)

    table.insert(ProceduralDistributions.list.MedicalClinicTools.items, "PercentTenRinge")
    table.insert(ProceduralDistributions.list.MedicalClinicTools.items, 17)
    table.insert(ProceduralDistributions.list.MedicalClinicTools.items, "RustRinges.PercentTwentyfiveRinge")
    table.insert(ProceduralDistributions.list.MedicalClinicTools.items, 11.2)
    table.insert(ProceduralDistributions.list.MedicalClinicTools.items, "RustRinges.PercentFiftyRinge")
    table.insert(ProceduralDistributions.list.MedicalClinicTools.items, 8.5)

    table.insert(ProceduralDistributions.list.MedicalStorageDrugs.items, "PercentTenRinge")
    table.insert(ProceduralDistributions.list.MedicalStorageDrugs.items, 17)
    table.insert(ProceduralDistributions.list.MedicalStorageDrugs.items, "RustRinges.PercentTwentyfiveRinge")
    table.insert(ProceduralDistributions.list.MedicalStorageDrugs.items, 11.2)
    table.insert(ProceduralDistributions.list.MedicalStorageDrugs.items, "RustRinges.PercentFiftyRinge")
    table.insert(ProceduralDistributions.list.MedicalStorageDrugs.items, 8.5)

    table.insert(ProceduralDistributions.list.MedicalStorageOutfit.items, "PercentTenRinge")
    table.insert(ProceduralDistributions.list.MedicalStorageOutfit.items, 17)
    table.insert(ProceduralDistributions.list.MedicalStorageOutfit.items, "RustRinges.PercentTwentyfiveRinge")
    table.insert(ProceduralDistributions.list.MedicalStorageOutfit.items, 11.2)
    table.insert(ProceduralDistributions.list.MedicalStorageOutfit.items, "RustRinges.PercentFiftyRinge")
    table.insert(ProceduralDistributions.list.MedicalStorageOutfit.items, 8.5)

    table.insert(ProceduralDistributions.list.MedicalStorageTools.items, "PercentTenRinge")
    table.insert(ProceduralDistributions.list.MedicalStorageTools.items, 17)
    table.insert(ProceduralDistributions.list.MedicalStorageTools.items, "RustRinges.PercentTwentyfiveRinge")
    table.insert(ProceduralDistributions.list.MedicalStorageTools.items, 11.2)
    table.insert(ProceduralDistributions.list.MedicalStorageTools.items, "RustRinges.PercentFiftyRinge")
    table.insert(ProceduralDistributions.list.MedicalStorageTools.items, 8.5)

    table.insert(ProceduralDistributions.list.PlankStashMoney.items, "PercentTenRinge")
    table.insert(ProceduralDistributions.list.PlankStashMoney.items, 17)
    table.insert(ProceduralDistributions.list.PlankStashMoney.items, "RustRinges.PercentTwentyfiveRinge")
    table.insert(ProceduralDistributions.list.PlankStashMoney.items, 11.2)
    table.insert(ProceduralDistributions.list.PlankStashMoney.items, "RustRinges.PercentFiftyRinge")
    table.insert(ProceduralDistributions.list.PlankStashMoney.items, 8.5)

    table.insert(ProceduralDistributions.list.SafehouseMedical.items, "PercentTenRinge")
    table.insert(ProceduralDistributions.list.SafehouseMedical.items, 17)
    table.insert(ProceduralDistributions.list.SafehouseMedical.items, "RustRinges.PercentTwentyfiveRinge")
    table.insert(ProceduralDistributions.list.SafehouseMedical.items, 11.2)
    table.insert(ProceduralDistributions.list.SafehouseMedical.items, "RustRinges.PercentFiftyRinge")
    table.insert(ProceduralDistributions.list.SafehouseMedical.items, 8.5)

    table.insert(ProceduralDistributions.list.TestingLab.items, "PercentTenRinge")
    table.insert(ProceduralDistributions.list.TestingLab.items, 17)
    table.insert(ProceduralDistributions.list.TestingLab.items, "RustRinges.PercentTwentyfiveRinge")
    table.insert(ProceduralDistributions.list.TestingLab.items, 11.2)
    table.insert(ProceduralDistributions.list.TestingLab.items, "RustRinges.PercentFiftyRinge")
    table.insert(ProceduralDistributions.list.TestingLab.items, 8.5)

    table.insert(ProceduralDistributions.list.StoreShelfMedical.items, "PercentTenRinge")
    table.insert(ProceduralDistributions.list.StoreShelfMedical.items, 17)
    table.insert(ProceduralDistributions.list.StoreShelfMedical.items, "RustRinges.PercentTwentyfiveRinge")
    table.insert(ProceduralDistributions.list.StoreShelfMedical.items, 11.2)
    table.insert(ProceduralDistributions.list.StoreShelfMedical.items, "RustRinges.PercentFiftyRinge")
    table.insert(ProceduralDistributions.list.StoreShelfMedical.items, 8.5)

    table.insert(ProceduralDistributions.list.DrugLabSupplies.items, "PercentTenRinge")
    table.insert(ProceduralDistributions.list.DrugLabSupplies.items, 17)
    table.insert(ProceduralDistributions.list.DrugLabSupplies.items, "RustRinges.PercentTwentyfiveRinge")
    table.insert(ProceduralDistributions.list.DrugLabSupplies.items, 11.2)
    table.insert(ProceduralDistributions.list.DrugLabSupplies.items, "RustRinges.PercentFiftyRinge")
    table.insert(ProceduralDistributions.list.DrugLabSupplies.items, 8.5)
end
local function highhealthringesspawn()
    table.insert(ProceduralDistributions.list.ArmyStorageMedical.items, "RustRinges.PercentFullRinge")
    table.insert(ProceduralDistributions.list.ArmyStorageMedical.items, 11)
    table.insert(ProceduralDistributions.list.BathroomCabinet.items, "RustRinges.PercentFullRinge")
    table.insert(ProceduralDistributions.list.BathroomCabinet.items, 3)
    table.insert(ProceduralDistributions.list.BathroomCounter.items, "RustRinges.PercentFullRinge")
    table.insert(ProceduralDistributions.list.BathroomCounter.items, 3)
    table.insert(ProceduralDistributions.list.BathroomShelf.items, "RustRinges.PercentFullRinge")
    table.insert(ProceduralDistributions.list.BathroomShelf.items, 3)
    table.insert(ProceduralDistributions.list.MedicalClinicDrugs.items, "RustRinges.PercentFullRinge")
    table.insert(ProceduralDistributions.list.MedicalClinicDrugs.items, 4)
    table.insert(ProceduralDistributions.list.MedicalStorageDrugs.items, "RustRinges.PercentFullRinge")
    table.insert(ProceduralDistributions.list.MedicalStorageDrugs.items, 4)
    table.insert(ProceduralDistributions.list.MedicalStorageTools.items, "RustRinges.PercentFullRinge")
    table.insert(ProceduralDistributions.list.MedicalStorageTools.items, 4)
    table.insert(ProceduralDistributions.list.PlankStashMoney.items, "RustRinges.PercentFullRinge")
    table.insert(ProceduralDistributions.list.PlankStashMoney.items, 6)
    table.insert(ProceduralDistributions.list.SafehouseMedical.items, "RustRinges.PercentFullRinge")
    table.insert(ProceduralDistributions.list.SafehouseMedical.items, 7)
    table.insert(ProceduralDistributions.list.TestingLab.items, "RustRinges.PercentFullRinge")
    table.insert(ProceduralDistributions.list.TestingLab.items, 5)
    table.insert(ProceduralDistributions.list.StoreShelfMedical.items, "RustRinges.PercentFullRinge")
    table.insert(ProceduralDistributions.list.StoreShelfMedical.items, 3)
    table.insert(ProceduralDistributions.list.DrugLabSupplies.items, "RustRinges.PercentFullRinge")
    table.insert(ProceduralDistributions.list.DrugLabSupplies.items, 6)
end
local function specializedringesspawn()
    table.insert(ProceduralDistributions.list.ArmyStorageMedical.items, "RustRinges.ThePristineCondition")
    table.insert(ProceduralDistributions.list.ArmyStorageMedical.items, 1)
    table.insert(ProceduralDistributions.list.MedicalClinicDrugs.items, "RustRinges.ThePristineCondition")
    table.insert(ProceduralDistributions.list.MedicalClinicDrugs.items, 1)
    table.insert(ProceduralDistributions.list.MedicalStorageDrugs.items, "RustRinges.ThePristineCondition")
    table.insert(ProceduralDistributions.list.MedicalStorageDrugs.items, 1)
    table.insert(ProceduralDistributions.list.MedicalStorageTools.items, "RustRinges.ThePristineCondition")
    table.insert(ProceduralDistributions.list.MedicalStorageTools.items, 1)
    table.insert(ProceduralDistributions.list.PlankStashMoney.items, "RustRinges.ThePristineCondition")
    table.insert(ProceduralDistributions.list.PlankStashMoney.items, 1)
    table.insert(ProceduralDistributions.list.SafehouseMedical.items, "RustRinges.ThePristineCondition")
    table.insert(ProceduralDistributions.list.SafehouseMedical.items, 1)
    table.insert(ProceduralDistributions.list.TestingLab.items, "RustRinges.ThePristineCondition")
    table.insert(ProceduralDistributions.list.TestingLab.items, 1)
    table.insert(ProceduralDistributions.list.StoreShelfMedical.items, "RustRinges.ThePristineCondition")
    table.insert(ProceduralDistributions.list.StoreShelfMedical.items, 1)
    table.insert(ProceduralDistributions.list.DrugLabSupplies.items, "RustRinges.ThePristineCondition")
    table.insert(ProceduralDistributions.list.DrugLabSupplies.items, 1)
end
local function zomboringesspawn()
    table.insert(ProceduralDistributions.list.ArmyStorageMedical.items, "RustRinges.ThePristineCondition35")
    table.insert(ProceduralDistributions.list.ArmyStorageMedical.items, 1)
    table.insert(ProceduralDistributions.list.ArmyStorageMedical.items, "RustRinges.InstantReliefRinge")
    table.insert(ProceduralDistributions.list.ArmyStorageMedical.items, 0.5)

    table.insert(ProceduralDistributions.list.BathroomCabinet.items, "RustRinges.InstantReliefRinge")
    table.insert(ProceduralDistributions.list.BathroomCabinet.items, 0.6)

    table.insert(ProceduralDistributions.list.BathroomCounter.items, "RustRinges.InstantReliefRinge")
    table.insert(ProceduralDistributions.list.BathroomCounter.items, 0.7)

    table.insert(ProceduralDistributions.list.BathroomShelf.items, "RustRinges.InstantReliefRinge")
    table.insert(ProceduralDistributions.list.BathroomShelf.items, 0.7)

    table.insert(ProceduralDistributions.list.MedicalClinicDrugs.items, "RustRinges.InstantReliefRinge")
    table.insert(ProceduralDistributions.list.MedicalClinicDrugs.items, 0.7)

    table.insert(ProceduralDistributions.list.MedicalClinicTools.items, "RustRinges.InstantReliefRinge")
    table.insert(ProceduralDistributions.list.MedicalClinicTools.items, 0.5)

    table.insert(ProceduralDistributions.list.MedicalStorageDrugs.items, "RustRinges.InstantReliefRinge")
    table.insert(ProceduralDistributions.list.MedicalStorageDrugs.items, 0.5)

    table.insert(ProceduralDistributions.list.MedicalStorageTools.items, "RustRinges.InstantReliefRinge")
    table.insert(ProceduralDistributions.list.MedicalStorageTools.items, 0.5)

    table.insert(ProceduralDistributions.list.PlankStashMoney.items, "RustRinges.InstantReliefRinge")
    table.insert(ProceduralDistributions.list.PlankStashMoney.items, 0.5)

    table.insert(ProceduralDistributions.list.SafehouseMedical.items, "RustRinges.ThePristineCondition35")
    table.insert(ProceduralDistributions.list.SafehouseMedical.items, 1)
    table.insert(ProceduralDistributions.list.SafehouseMedical.items, "RustRinges.InstantReliefRinge")
    table.insert(ProceduralDistributions.list.SafehouseMedical.items, 3)

    table.insert(ProceduralDistributions.list.TestingLab.items, "RustRinges.ThePristineCondition35")
    table.insert(ProceduralDistributions.list.TestingLab.items, 1)
    table.insert(ProceduralDistributions.list.TestingLab.items, "RustRinges.InstantReliefRinge")
    table.insert(ProceduralDistributions.list.TestingLab.items, 0.5)

    table.insert(ProceduralDistributions.list.DrugLabSupplies.items, "RustRinges.ThePristineCondition35")
    table.insert(ProceduralDistributions.list.DrugLabSupplies.items, 1)
    table.insert(ProceduralDistributions.list.DrugLabSupplies.items, "RustRinges.InstantReliefRinge")
    table.insert(ProceduralDistributions.list.DrugLabSupplies.items, 2)
end


Events.OnPostDistributionMerge.Add(zomboringesspawn)
Events.OnPostDistributionMerge.Add(specializedringesspawn)
Events.OnPostDistributionMerge.Add(lowhealthringesspawn)
Events.OnPostDistributionMerge.Add(highhealthringesspawn)